spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1   # PDB 이름
    username: spring                               # 스키마(유저) 이름
    password: java123                          # 스키마 비밀번호

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.project.board
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'